# Run a quorum of three Zeebe brokers. Two of these are on
# Kubernetes, with only one of them writing its Raft log onto NFS (for
# fault tolerance purposes, we don't want a majority of the brokers
# doing that). The third one (numbered 0) is on a VM (see
# ../../epfl.esb-vm/tasks/zeebe.yml).

- tags: always
  include_vars: common-k8s-vars.yml

# Node 0 is on Kubernetes only for the test namespace
# (in prod, it lives on the VM for persistence diversity)
- import_tasks: _zeebe-k8s-broker.yml
  when: >-
    "test" in openshift_namespace
  vars:
    node_id: 0
    data_volume:
      emptyDir: {}
    peers:
      - "zeebe-quorum-2:{{ zeebe_ports.quorum }}"
      - "zeebe-quorum-1:{{ zeebe_ports.quorum }}"
  tags:
    - zeebe-ha
    - zeebe-ha-0

- import_tasks: _zeebe-k8s-broker.yml
  vars:
    node_id: 1
    data_volume:
      persistentVolumeClaim:
        claimName: "{{ volume_zeebe_name }}"
    peers:
      - "zeebe-quorum-0:{{ zeebe_ports.quorum }}"
      - "zeebe-quorum-2:{{ zeebe_ports.quorum }}"
  tags:
    - zeebe-ha
    - zeebe-ha-1

- import_tasks: _zeebe-k8s-broker.yml
  vars:
    node_id: 2
    data_volume:
      emptyDir: {}
    peers:
      - "zeebe-quorum-0:{{ zeebe_ports.quorum }}"
      - "zeebe-quorum-1:{{ zeebe_ports.quorum }}"
  tags:
    - zeebe-ha
    - zeebe-ha-2

- name: Quorum Services
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: "{{ item }}"
      namespace: "{{ openshift_namespace }}"
    spec:
      type: ClusterIP
      ports:
        - name: "zeebe-raft"
          port: "{{ zeebe_ports.quorum }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.quorum }}"
        - name: "zeebe-command"
          port: "{{ zeebe_ports.command }}"
          protocol: TCP
          targetPort: "{{ zeebe_ports.command }}"
      selector:
        zeebe-quorum-member: "{{ item }}"
  with_items: "{{ _zeebe_quorum_services }}"
  vars:
    _zeebe_quorum_services: >-
      {{
      ["zeebe-quorum-0", "zeebe-quorum-1", "zeebe-quorum-2"]
      if "test" in openshift_namespace
      else esb_ssh_tunnels.reverse.zeebe | map(attribute="name")
      }}
