# This is the dev-only Dockerfile used trough ../docker-compose.yml
FROM camunda/zeebe:8.2.4

#ADD https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/download/1.0.1/zeebe-hazelcast-exporter-1.0.1-jar-with-dependencies.jar /usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar
#ADD https://github.com/camunda-community-hub/zeebe-kafka-exporter/releases/download/3.0.0/zeebe-kafka-exporter-3.0.0-jar-with-dependencies.jar /usr/local/zeebe/lib/zeebe-kafka-exporter-with-dependencies.jar
#ADD https://github.com/crossid/zeebe-mongo-exporter/releases/download/v0.4.1/zeebe-mongo-exporter.jar /usr/local/zeebe/lib/zeebe-mongo-exporter.jar

#RUN chmod 755 /usr/local/zeebe/lib/*jar
